"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class cell_coordinate_t(object):
    __slots__ = ["x", "y"]

    __typenames__ = ["int64_t", "int64_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.x = 0
        self.y = 0

    def encode(self):
        buf = BytesIO()
        buf.write(cell_coordinate_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qq", self.x, self.y))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cell_coordinate_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cell_coordinate_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = cell_coordinate_t()
        self.x, self.y = struct.unpack(">qq", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if cell_coordinate_t in parents: return 0
        tmphash = (0xa1d9c701af074f64) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if cell_coordinate_t._packed_fingerprint is None:
            cell_coordinate_t._packed_fingerprint = struct.pack(">Q", cell_coordinate_t._get_hash_recursive([]))
        return cell_coordinate_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

